### ISSUE TITLE
pyp doesn't add requirements in alphabetical order

### ISSUE THREAD

**Issue by zachtylr21** [zachtylr21/pyp#1]
- Version update: minor

**Comment by ankush981** [comment]
Hello, nice project (saw it on Dev.to first)! I'm not a seasoned Python dev but very comfortable and know a few gotchas as well. Can I take up this issue? 😄

**Comment by zachtylr21** [comment]
@ankush981 Glad you like it. 😄 Sure, I'd be happy to have you take this on!

**Comment by ankush981** [comment]
Thank you so much! I'll try my best to do this asap. Will be very happy to receive any feedback and improve the solution. By the way, if I have any questions, where do I ask?

**Comment by zachtylr21** [comment]
Awesome. If you have questions, I think here on this issue thread would be a convenient place to do that for now. And if you have any ideas for how the project could be improved, feel free to create issues for them!

**Comment by ankush981** [comment]
Hello, so, I sent a pull request. Sorry for the delay; I really wanted to crank it out last weekend but got lazy. 😆

**Comment by zachtylr21** [comment]
No worries! I'll review it and get back to you soon

**Comment by zachtylr21** [comment]
This was fixed by #5

**Comment by zachtylr21** [comment]
This was fixed by #5
