### ISSUE TITLE
Pytest error

### ISSUE THREAD

**Issue by zachtylr21** [zachtylr21/pyp#9]
@ankush981 reported seeing an error when running the tests. The error was 

```
int: make sure your test modules/packages have valid Python names.
Traceback:
../../../../.pyenv/versions/3.7.9/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_all.py:3: in <module>
    from pyp.pyp import pip_freeze, sort_entries
E   ModuleNotFoundError: No module named 'pyp'
```

**Comment by ankush981** [comment]
Well, solved it, finally. So, as the error mentions, pyp is a dependency to run the tests, apparently. But I was doing `pip install pyp`, which was installing something else (of course). 😅 Finally I did `pip install pyp-manager` and now simply running `pytest` shows passing tests. 👍 Normally the package executables and pip packages have the same names, which is what got me here.

**Comment by zachtylr21** [comment]
Oh that makes sense. Maybe we'll have to change the project name in a later version to not clash with the existing `pyp` package... we'll see. I'll close this issue since it seems the problem has been resolved. 😄

**Comment by ankush981** [comment]
Actually, as I write the documentation, I'm wondering if the above was really a solution. Why should `pyp-manager` be a requirement for running the tests if we want to run tests on code that someone has written just now? Am I missing something here? 🤔 

Anyway, I'll submit the documentation PR regardless and we can discuss this.

**Comment by zachdtaylor** [comment]
That's a good point, I'm not sure why `pyp-manager` would be a requirement for running the tests. We'll have to look into it further.
